version: "3.7"

services:

  dev_clickhouse_server:
    image: clickhouse/clickhouse-server:22.6
    ports:
      - 8143:8123
      - 9000:9000
    volumes:
      - ./dev/clickhouse:/var/lib/clickhouse

  # dev_front_basicrum_go:
  #   image: golang:1.18
  #   volumes:
  #     - ./:/go/src/github.com/basicrum/front_basicrum_go
  #     - ./certs:/certs
  #   working_dir: /go/src/github.com/basicrum/front_basicrum_go
  #   ports:
  #     - 8087:8087
  #   command: >
  #     sh -c "go mod tidy &&
  #            go run . -domain localhost &&
  #            ./main"
