version: "3.7"

services:

  dev_clickhouse_server:
    image: clickhouse/clickhouse-server:22.6
    ports:
      - 8143:8123
      - 9000:9000
    volumes:
      - ./dev/clickhouse:/var/lib/clickhouse