server:
  host: "localhost"
  port: 8087

database:
  host: "localhost"
  port: 9000
  database_name: "default"
  username: "default"
  password: ""
  table_prefix: "integration_test"

persistance:
  database_strategy: all_in_one_db
  table_strategy: all_in_one_table